server:
  port: 8100
spring:
  application:
    name: ZUUL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
zuul:
  routes:
    SERVICE_NEW: /sn/**
    SERVICE: /s/**
  ignored-services:
    SERVICE
